
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-app
  labels:
    app: authentication-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service-app
  template:
    metadata:
      labels:
        app: authentication-service-app
    spec:
      containers:
        - name: authentication-service-app
          image: kaveeshalk/authentication-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9898

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-svc
spec:
  ports:
    - targetPort: 9898
      port: 80
  selector:
    app: authentication-service-app
